from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.
class Clown(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField(default=1)
    description = models.CharField(max_length=500)
    slug = models.CharField(max_length=600, blank=True, editable=False,
                            help_text="Unique URL path to access this page. Generated by the system.")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """ Returns a fully-qualified path for a Clown. """
        path_components = {'slug': self.slug}
        return reverse('resume-details-page', kwargs=path_components)

    def save(self, *args, **kwargs):
        """ Creates a URL safe slug automatically when a new a resume is created. """
        if not self.pk:
            self.slug = slugify(self.name, allow_unicode=True)

        # Call save on the superclass.
        return super(Clown, self).save(*args, **kwargs)


class Group(models.Model):
    name = models.CharField(max_length=200)
    #performers = models.ForeignKey(Group, on_delete=models.CASCADE)
    description = models.CharField(max_length=500)